name: Deploy Workflow

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-1
  S3BUCKET: saeed-app

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      s3object: ${{ steps.object.outputs.s3object }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
    
    - name: Package Repo and Upload to S3
      id: object
      run: |
        DATE=$(date +%Y%m%d)
        s3object=$(echo "app_${DATE}.tar.gz")
        echo "S3 Object: $s3object"
        echo "s3object=$s3object" >> $GITHUB_OUTPUT
        # Archive the repository
        git archive --format=tar.gz --output=${s3object} HEAD
        mkdir archive
        mv ${s3object} archive/
        ls archive
        aws s3 cp archive/${s3object} s3://${{ env.S3BUCKET }}/${s3object}
    
    - name: Create an Expiry ploicy
      run: |
        aws s3api put-bucket-lifecycle-configuration --bucket ${{ env.S3BUCKET }} --lifecycle-configuration '{"Rules":[{"ID":"DeleteObjectsAfter7Days","Prefix":"","Status":"Enabled","Expiration":{"Days":7}}]}'


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC

    - name: Deploy to Auto Scaling Group
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_PEM }}
      run: |
        aws autoscaling update-auto-scaling-group --auto-scaling-group-name saeed --launch-template LaunchTemplateId=lt-0ebf36a7c09b03a8e,Version=Latest
