name: Deploy Workflow

on:
  workflow_dispatch: {}
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-1
  S3BUCKET: saeed-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Package Repo
      run: |
        DATE=$(date +%Y%m%d)
        S3OBJECT="app_${DATE}.tar.gz"
        git archive --format=tar.gz --output=${S3OBJECT} HEAD
        mkdir archive
        mv ${S3OBJECT} archive/
        ls archive
      
    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@master
      env:
        AWS_S3_BUCKET: ${{ env.S3BUCKET }}
        AWS_REGION: ${{ env.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'archive'

    - name: Deploy to Auto Scaling Group
      run: |
        echo "deploy to Auto Scaling Group"
