name: wordpress-deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.vars.outputs.TAG }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set tag value from short git commit SHA
        id: vars
        run: |
          TAG=$(git rev-parse --short ${{ github.sha }})
          # save state
          echo "TAG=$TAG" >> $GITHUB_ENV
          # set output
          echo "TAG=$TAG" >> $GITHUB_OUTPUT
      
      - name: Confirm tag output
        run: echo $TAG
      
      - name: Build and push
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/saeed-wordpress:$TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/saeed-wordpress:$TAG


  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
